import { HikingRecord } from '../types';

const STORAGE_KEY = 'summitlog_data_v3'; // Bump version to force load new seed data

export const loadRecords = (): HikingRecord[] => {
  try {
    const data = localStorage.getItem(STORAGE_KEY);
    return data ? JSON.parse(data) : [];
  } catch (error) {
    console.error("Failed to load records from local storage", error);
    return [];
  }
};

export const saveRecords = (records: HikingRecord[]): void => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(records));
  } catch (error) {
    console.error("Failed to save records to local storage", error);
  }
};

export const clearRecords = (): void => {
  localStorage.removeItem(STORAGE_KEY);
};

// Seed data based on user input
export const getSeedData = (): HikingRecord[] => [
  {
    id: '1',
    date: '2025-03-08',
    name: '云海广场',
    distanceKm: 4.02,
    elevationGainM: 494,
    durationHours: 2.4,
    calories: 480,
    startPoint: '盐田路地铁站',
    endPoint: '云海广场',
    difficultyScore: 1.5,
    sceneryScore: 3.0,
    notes: '下山公交',
  },
  {
    id: '2',
    date: '2025-03-16',
    name: '五园连通',
    distanceKm: 13.66,
    elevationGainM: 750,
    durationHours: 4.6,
    calories: 1103,
    startPoint: '梅林水库',
    endPoint: '莲花山-深业上城',
    difficultyScore: 2.0,
    sceneryScore: 3.0,
    notes: '',
  },
  {
    id: '3',
    date: '2025-03-23',
    name: '阳台山',
    distanceKm: 8.02,
    elevationGainM: 639,
    durationHours: 3.7,
    calories: 868,
    startPoint: '王京坑登山口',
    endPoint: '大浪文化公园',
    difficultyScore: 2.0,
    sceneryScore: 3.0,
    notes: '',
  },
  {
    id: '4',
    date: '2025-03-29',
    name: '马峦山',
    distanceKm: 13.48,
    elevationGainM: 431,
    durationHours: 4.4,
    calories: 824,
    startPoint: '马峦山北门游客中心',
    endPoint: '大梅沙地铁站',
    difficultyScore: 2.0,
    sceneryScore: 3.0,
    notes: '',
  },
  {
    id: '5',
    date: '2025-04-04',
    name: '塘朗山',
    distanceKm: 11.25,
    elevationGainM: 401,
    durationHours: 3.95,
    calories: 861,
    startPoint: '南山智园',
    endPoint: '星河coco city',
    difficultyScore: 1.5,
    sceneryScore: 3.0,
    notes: '',
  },
  {
    id: '6',
    date: '2025-04-06',
    name: '银湖山',
    distanceKm: 8.89,
    elevationGainM: 642,
    durationHours: 3.47,
    calories: 877,
    startPoint: '银湖地铁站',
    endPoint: '雅宝地铁站',
    difficultyScore: 1.5,
    sceneryScore: 3.0,
    notes: '',
  },
  {
    id: '7',
    date: '2025-04-13',
    name: '七娘山',
    distanceKm: 14.43,
    elevationGainM: 938,
    durationHours: 7.17,
    calories: 1321,
    startPoint: '大鹏新大社区-大榕树',
    endPoint: '大鹏新大社区-主峰科考线',
    difficultyScore: 3.0,
    sceneryScore: 3.0,
    notes: '',
  },
  {
    id: '8',
    date: '2025-04-26',
    name: '塘朗山',
    distanceKm: 7.71,
    elevationGainM: 432,
    durationHours: 4.23,
    calories: 793,
    startPoint: '塘朗村',
    endPoint: '塘朗村',
    difficultyScore: 1.5,
    sceneryScore: 3.0,
    notes: '',
  },
  {
    id: '9',
    date: '2025-05-02',
    name: '肇庆羚羊峡古道',
    distanceKm: 4.18,
    elevationGainM: 62,
    durationHours: 1.3,
    calories: 276,
    startPoint: '羚山涌码头',
    endPoint: '羚山涌码头',
    difficultyScore: 0.5,
    sceneryScore: 3.0,
    notes: '',
  },
  {
    id: '10',
    date: '2025-05-02',
    name: '肇庆鼎湖山',
    distanceKm: 8.43,
    elevationGainM: 244,
    durationHours: 4.03,
    calories: 613,
    startPoint: '鼎湖山景区',
    endPoint: '鼎湖山景区',
    difficultyScore: 1.0,
    sceneryScore: 3.0,
    notes: '',
  },
  {
    id: '11',
    date: '2025-05-04',
    name: '阳台山',
    distanceKm: 8.42,
    elevationGainM: 436,
    durationHours: 3.6,
    calories: 762,
    startPoint: '麻磡',
    endPoint: '石岩环湖碧道万象广场',
    difficultyScore: 1.5,
    sceneryScore: 3.0,
    notes: '',
  },
  {
    id: '12',
    date: '2025-05-11',
    name: '梅沙尖',
    distanceKm: 15.39,
    elevationGainM: 1130,
    durationHours: 6.22,
    calories: 1549,
    startPoint: '盐田路地铁站',
    endPoint: '大梅沙地铁站',
    difficultyScore: 3.0,
    sceneryScore: 3.0,
    notes: '',
  },
  {
    id: '13',
    date: '2025-05-24',
    name: '阳台山',
    distanceKm: 11.56,
    elevationGainM: 727,
    durationHours: 5.58,
    calories: 1164,
    startPoint: '阳台山森林公园大门',
    endPoint: '官田地铁站',
    difficultyScore: 1.5,
    sceneryScore: 3.0,
    notes: '下山错路',
  },
  {
    id: '14',
    date: '2025-06-01',
    name: '广西圣堂山',
    distanceKm: 11.51,
    elevationGainM: 801,
    durationHours: 5.37,
    calories: 1157,
    startPoint: '圣堂山景区',
    endPoint: '圣堂山景区',
    difficultyScore: 2.5,
    sceneryScore: 3.0,
    notes: '',
  },
  {
    id: '15',
    date: '2025-10-26',
    name: '马峦山',
    distanceKm: 10.99,
    elevationGainM: 289,
    durationHours: 5.43,
    calories: 821,
    startPoint: '黄竹坑',
    endPoint: '小梅沙地铁站',
    difficultyScore: 1.5,
    sceneryScore: 3.0,
    notes: '',
  },
  {
    id: '16',
    date: '2025-11-01',
    name: '大雁顶',
    distanceKm: 10.17,
    elevationGainM: 820,
    durationHours: 6.67,
    calories: 1225,
    startPoint: '杨梅坑天然潭',
    endPoint: '鹿嘴山庄',
    difficultyScore: 3.0,
    sceneryScore: 3.0,
    notes: '无人河谷爬升',
  },
  {
    id: '17',
    date: '2025-11-08',
    name: '打鼓嶂-圆山',
    distanceKm: 12.26,
    elevationGainM: 840,
    durationHours: 7.18,
    calories: 1395,
    startPoint: '新沙混凝土公司',
    endPoint: '圆山地铁站',
    difficultyScore: 2.5,
    sceneryScore: 3.0,
    notes: '中段平坦',
  },
  {
    id: '18',
    date: '2025-11-15',
    name: '梅沙尖',
    distanceKm: 8.08,
    elevationGainM: 835,
    durationHours: 5.0,
    calories: 1057,
    startPoint: '盐田路地铁站',
    endPoint: '山海大观',
    difficultyScore: 2.0,
    sceneryScore: 3.0,
    notes: '团队爬山',
  },
  {
    id: '19',
    date: '2025-11-16',
    name: '小梧桐-植物园',
    distanceKm: 8.54,
    elevationGainM: 586,
    durationHours: 3.33,
    calories: 897,
    startPoint: '梧桐山南地铁站',
    endPoint: '仙湖路地铁站',
    difficultyScore: 1.5,
    sceneryScore: 3.0,
    notes: '',
  }
];